export default dummy_data = {
  kind: "youtube#videoListResponse",
  etag: "hovIyfmcbNrdyRu164qKmUjXTbI",
  items: [
    {
      kind: "youtube#video",
      etag: "wwp6r2rISBAdPxoP5PrPu70PdXw",
      id: "kcNpBNpvyc4",
      snippet: {
        publishedAt: "2020-11-06T18:30:10Z",
        channelId: "UC3tMH8u6yG3mSxi-qpfmpkA",
        title: "asdfmovie 1-13 (Complete Collection)",
        description:
          "Muffin Time: the asdfmovie card game! Out now! http://MuffinTimeGame.com\nasdfmovie merch (http://sharkrobot.com/asdfmovie)\nMore asdfmovie (including the songs)! https://www.youtube.com/playlist?list=PL3A5849BDE0581B19\n\nasdfmovie1 animated by James 'GlassCake' Cunningham (http://youtube.com/glasscake)\nasdfmovie2 / asdfmovie2: deleted scenes / asdfmite animated by Edd 'Eddsworld' Gould (http://www.youtube.com/eddsworld)\nasdfmovie3 + 5 animated by Jamie 'RageNineteen' Spicer-Lewis (http://www.youtube.com/ragenineteen)\nasdfmovie4/6/7/deleted scenes/8/9/10/11/12/deleted scenes/13 animated by Ben 'Wonchop' Smallman (http://youtube.com/WonchopAnimation)\nMusic by Todd 'LilDeuceDeuce' Bryanton (http://youtube.com/LilDeuceDeuce)\n\nFor cast/additional credits, watch the actual asdfmovies, ya goober.\n\nMain Channel (http://youtube.com/TomSka)\nReddit (http://reddit.com/r/tomska)\nTwitter (http://twitter.com/thetomska)\nFacebook (http://fb.com/thetomska)\nTumblr (http://thetomska.tumblr.com)\n\nasdfmovie1 0:00\nasdfmovie2 1:28\nasdfmovie2: deleted scenes 3:10\nasdfmite 3:49\nasdfmovie3 4:28\nasdfmovie4 5:46\ni like skyrims 7:11\nasdfmovie5 7:17\nasdfmovie6 8:38\nasdfmovie7 10:10\nasdfmovie: deleted scenes 11:40\nasdfmovie8 13:38\nasdfmovie9 15:17\nasdfmovie10 16:55\nasdfmovie11 18:53\nit's muffin time! 21:04\nasdfmovie12 21:13\nasdfmovie12: deleted scenes 23:27\nasdfmovie13 24:25\nasdfcredits 26:31\nasdfmerch 27:58",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/kcNpBNpvyc4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/kcNpBNpvyc4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/kcNpBNpvyc4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/kcNpBNpvyc4/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/kcNpBNpvyc4/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "TomSka & Friends",
        tags: [
          "tomska",
          "asdf",
          "adsf",
          "asf",
          "fasd",
          "fsda",
          "asdf movie",
          "random",
          "cartoon",
          "trains",
          "muffin",
          "pie",
          "sheep",
          "beep",
          "cow",
          "waffle",
          "collection",
          "compilation",
          "meme",
          "asdfmovie",
          "asdfmovie13",
          "tik tok",
          "markiplier",
          "song",
          "movie",
          "try not to laugh",
          "among us",
          "tiktok",
          "youtube",
          "memes",
          "funny videos",
          "unus annus",
          "funny",
          "tik tok songs",
          "comedy",
          "sketch",
          "tik tok video",
          "video",
          "i love it",
          "pizza time",
          "schmoyoho",
          "horse",
          "thomas ridgewell",
          "notasdfmovie",
          "lol",
          "animation",
          "ytp",
          "tik tok dance",
          "meme compilation",
          "tik tok song",
          "jacksfilms",
          "tik tok memes",
          "tik toks",
        ],
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "asdfmovie 1-13 (Complete Collection)",
          description:
            "Muffin Time: the asdfmovie card game! Out now! http://MuffinTimeGame.com\nasdfmovie merch (http://sharkrobot.com/asdfmovie)\nMore asdfmovie (including the songs)! https://www.youtube.com/playlist?list=PL3A5849BDE0581B19\n\nasdfmovie1 animated by James 'GlassCake' Cunningham (http://youtube.com/glasscake)\nasdfmovie2 / asdfmovie2: deleted scenes / asdfmite animated by Edd 'Eddsworld' Gould (http://www.youtube.com/eddsworld)\nasdfmovie3 + 5 animated by Jamie 'RageNineteen' Spicer-Lewis (http://www.youtube.com/ragenineteen)\nasdfmovie4/6/7/deleted scenes/8/9/10/11/12/deleted scenes/13 animated by Ben 'Wonchop' Smallman (http://youtube.com/WonchopAnimation)\nMusic by Todd 'LilDeuceDeuce' Bryanton (http://youtube.com/LilDeuceDeuce)\n\nFor cast/additional credits, watch the actual asdfmovies, ya goober.\n\nMain Channel (http://youtube.com/TomSka)\nReddit (http://reddit.com/r/tomska)\nTwitter (http://twitter.com/thetomska)\nFacebook (http://fb.com/thetomska)\nTumblr (http://thetomska.tumblr.com)\n\nasdfmovie1 0:00\nasdfmovie2 1:28\nasdfmovie2: deleted scenes 3:10\nasdfmite 3:49\nasdfmovie3 4:28\nasdfmovie4 5:46\ni like skyrims 7:11\nasdfmovie5 7:17\nasdfmovie6 8:38\nasdfmovie7 10:10\nasdfmovie: deleted scenes 11:40\nasdfmovie8 13:38\nasdfmovie9 15:17\nasdfmovie10 16:55\nasdfmovie11 18:53\nit's muffin time! 21:04\nasdfmovie12 21:13\nasdfmovie12: deleted scenes 23:27\nasdfmovie13 24:25\nasdfcredits 26:31\nasdfmerch 27:58",
        },
        defaultAudioLanguage: "en-GB",
      },
      contentDetails: {
        duration: "PT28M43S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {
          ytRating: "ytAgeRestricted",
        },
        projection: "rectangular",
      },
      statistics: {
        viewCount: "18168876",
        likeCount: "348271",
        favoriteCount: "0",
        commentCount: "22584",
      },
    },
    {
      kind: "youtube#video",
      etag: "Rwvu_taPqhpnlNz7IANS_qCB3ig",
      id: "jjS5UTRE8zY",
      snippet: {
        publishedAt: "2021-06-25T21:17:33Z",
        channelId: "UC0RvBTXBHt1GSXDHtfruiBg",
        title: "asdfmovie 1-14 (Complete Collection)",
        description:
          "The complete collection of asdfmovie\n\nall 14 shorts \n\nCredits: Tomska",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/jjS5UTRE8zY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/jjS5UTRE8zY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/jjS5UTRE8zY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "zenchi",
        tags: [
          "asdfmovie14",
          "asdfmovie",
          "asdfmovie collection",
          "asdfmovie 14",
          "asdfmovie 1-14",
          "asdfmovie 1-14 collection",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "asdfmovie 1-14 (Complete Collection)",
          description:
            "The complete collection of asdfmovie\n\nall 14 shorts \n\nCredits: Tomska",
        },
      },
      contentDetails: {
        duration: "PT31M44S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1461058",
        likeCount: "34058",
        favoriteCount: "0",
        commentCount: "1838",
      },
    },
    {
      kind: "youtube#video",
      etag: "F8gcieDhTxtnBHMlos9kpfBqCK0",
      id: "PXGljpsidd4",
      snippet: {
        publishedAt: "2013-05-05T07:40:31Z",
        channelId: "UCB28dGCZZXAmIljqvjIt9AQ",
        title: "ASDF Movie 1,2,3,4,5,6",
        description:
          "I did not make these animations. All rights go to TomSka.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/PXGljpsidd4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/PXGljpsidd4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/PXGljpsidd4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/PXGljpsidd4/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/PXGljpsidd4/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "DS123",
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "ASDF Movie 1,2,3,4,5,6",
          description:
            "I did not make these animations. All rights go to TomSka.",
        },
      },
      contentDetails: {
        duration: "PT9M24S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "3688740",
        likeCount: "24869",
        favoriteCount: "0",
        commentCount: "2996",
      },
    },
  ],
  pageInfo: {
    totalResults: 3,
    resultsPerPage: 3,
  },
};
